FROM openjdk:11

WORKDIR /app

ADD ./target/authentication-server-0.0.1-SNAPSHOT.jar /app/authentication-server-0.0.1-SNAPSHOT.jar



ENTRYPOINT ["java","-jar", "authentication-server-0.0.1-SNAPSHOT.jar"]
